# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMAC.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nHMAC.proto\x12\rcrypto_condor\"u\n\x0cHmacNistTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0c\n\x04klen\x18\x02 \x01(\x05\x12\x0c\n\x04tlen\x18\x03 \x01(\x05\x12\x0b\n\x03key\x18\x04 \x01(\x0c\x12\x0b\n\x03msg\x18\x05 \x01(\x0c\x12\x0b\n\x03mac\x18\x06 \x01(\x0c\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"a\n\x0fHmacNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08hashname\x18\x02 \x01(\t\x12*\n\x05tests\x18\x03 \x03(\x0b\x32\x1b.crypto_condor.HmacNistTest\"z\n\x12HmacWycheproofTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x12\x0b\n\x03msg\x18\x04 \x01(\x0c\x12\x0b\n\x03mac\x18\x05 \x01(\x0c\x12\x0e\n\x06result\x18\x06 \x01(\t\x12\r\n\x05\x66lags\x18\x07 \x03(\t\"k\n\x13HmacWycheproofGroup\x12\x10\n\x08key_size\x18\x01 \x01(\x05\x12\x10\n\x08tag_size\x18\x02 \x01(\x05\x12\x30\n\x05tests\x18\x03 \x03(\x0b\x32!.crypto_condor.HmacWycheproofTest\"\x98\x02\n\x15HmacWycheproofVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\talgorithm\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06header\x18\x04 \x03(\t\x12\x17\n\x0fnumber_of_tests\x18\x05 \x01(\x05\x12>\n\x05notes\x18\x06 \x03(\x0b\x32/.crypto_condor.HmacWycheproofVectors.NotesEntry\x12\x32\n\x06groups\x18\x07 \x03(\x0b\x32\".crypto_condor.HmacWycheproofGroup\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HMAC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HMACWYCHEPROOFVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_HMACWYCHEPROOFVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_HMACNISTTEST']._serialized_start=29
  _globals['_HMACNISTTEST']._serialized_end=146
  _globals['_HMACNISTVECTORS']._serialized_start=148
  _globals['_HMACNISTVECTORS']._serialized_end=245
  _globals['_HMACWYCHEPROOFTEST']._serialized_start=247
  _globals['_HMACWYCHEPROOFTEST']._serialized_end=369
  _globals['_HMACWYCHEPROOFGROUP']._serialized_start=371
  _globals['_HMACWYCHEPROOFGROUP']._serialized_end=478
  _globals['_HMACWYCHEPROOFVECTORS']._serialized_start=481
  _globals['_HMACWYCHEPROOFVECTORS']._serialized_end=761
  _globals['_HMACWYCHEPROOFVECTORS_NOTESENTRY']._serialized_start=717
  _globals['_HMACWYCHEPROOFVECTORS_NOTESENTRY']._serialized_end=761
# @@protoc_insertion_point(module_scope)
