# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _slhdsa/slhdsa.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14_slhdsa/slhdsa.proto\x12\rcrypto_condor\"\xc0\x01\n\nSlhdsaTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\n\n\x02sk\x18\x05 \x01(\x0c\x12\n\n\x02pk\x18\x06 \x01(\x0c\x12\x0b\n\x03msg\x18\x07 \x01(\x0c\x12\x0b\n\x03sig\x18\x08 \x01(\x0c\x12\x0b\n\x03\x63tx\x18\t \x01(\x0c\x12\n\n\x02ph\x18\n \x01(\t\x12\x0e\n\x06skseed\x18\x0b \x01(\x0c\x12\r\n\x05skprf\x18\x0c \x01(\x0c\x12\x0e\n\x06pkseed\x18\r \x01(\x0c\"\xa2\x02\n\rSlhdsaVectors\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bsource_desc\x18\x02 \x01(\t\x12\x12\n\nsource_url\x18\x03 \x01(\t\x12\x12\n\ncompliance\x18\x04 \x01(\x08\x12\x36\n\x05notes\x18\x05 \x03(\x0b\x32\'.crypto_condor.SlhdsaVectors.NotesEntry\x12(\n\x05tests\x18\x06 \x03(\x0b\x32\x19.crypto_condor.SlhdsaTest\x12\x11\n\toperation\x18\x07 \x01(\t\x12\x10\n\x08paramset\x18\x08 \x01(\t\x12\x0f\n\x07prehash\x18\t \x01(\x08\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_slhdsa.slhdsa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SLHDSAVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_SLHDSAVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_SLHDSATEST']._serialized_start=40
  _globals['_SLHDSATEST']._serialized_end=232
  _globals['_SLHDSAVECTORS']._serialized_start=235
  _globals['_SLHDSAVECTORS']._serialized_end=525
  _globals['_SLHDSAVECTORS_NOTESENTRY']._serialized_start=481
  _globals['_SLHDSAVECTORS_NOTESENTRY']._serialized_end=525
# @@protoc_insertion_point(module_scope)
