# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyber.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bkyber.proto\x12\rcrypto_condor\"\\\n\rKyberNistTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0c\n\x04seed\x18\x02 \x01(\x0c\x12\n\n\x02pk\x18\x03 \x01(\x0c\x12\n\n\x02sk\x18\x04 \x01(\x0c\x12\n\n\x02\x63t\x18\x05 \x01(\x0c\x12\n\n\x02ss\x18\x06 \x01(\x0c\"M\n\x10KyberNistVectors\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x05tests\x18\x02 \x03(\x0b\x32\x1c.crypto_condor.KyberNistTestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kyber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KYBERNISTTEST']._serialized_start=30
  _globals['_KYBERNISTTEST']._serialized_end=122
  _globals['_KYBERNISTVECTORS']._serialized_start=124
  _globals['_KYBERNISTVECTORS']._serialized_end=201
# @@protoc_insertion_point(module_scope)
