# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rsa.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trsa.proto\x12\rcrypto_condor\"[\n\x11RsaNistSigGenTest\x12\x0b\n\x03\x61lg\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0b\n\x03sig\x18\x03 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05J\x04\x08\x04\x10\x05R\x04salt\"\x87\x01\n\x14RsaNistSigGenVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0b\n\x03mod\x18\x02 \x01(\x05\x12\t\n\x01n\x18\x03 \x01(\t\x12\t\n\x01\x65\x18\x04 \x01(\t\x12\t\n\x01\x64\x18\x05 \x01(\t\x12/\n\x05tests\x18\x0f \x03(\x0b\x32 .crypto_condor.RsaNistSigGenTest\"\x8d\x01\n\x11RsaNistSigVerTest\x12\t\n\x01\x65\x18\x01 \x01(\t\x12\t\n\x01\x64\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\x0b\n\x03sig\x18\x05 \x01(\t\x12\x0c\n\x04salt\x18\x06 \x01(\t\x12\x0e\n\x06result\x18\t \x01(\x08\x12\x0e\n\x06reason\x18\n \x01(\tJ\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tR\x02\x65mR\nem_comment\"\x8e\x01\n\x14RsaNistSigVerVectors\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03mod\x18\x02 \x01(\x05\x12\t\n\x01n\x18\x03 \x01(\t\x12\t\n\x01p\x18\x04 \x01(\t\x12\t\n\x01q\x18\x05 \x01(\t\x12\x0b\n\x03sha\x18\x07 \x01(\t\x12/\n\x05tests\x18\x08 \x03(\x0b\x32 .crypto_condor.RsaNistSigVerTestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rsa_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RSANISTSIGGENTEST']._serialized_start=28
  _globals['_RSANISTSIGGENTEST']._serialized_end=119
  _globals['_RSANISTSIGGENVECTORS']._serialized_start=122
  _globals['_RSANISTSIGGENVECTORS']._serialized_end=257
  _globals['_RSANISTSIGVERTEST']._serialized_start=260
  _globals['_RSANISTSIGVERTEST']._serialized_end=401
  _globals['_RSANISTSIGVERVECTORS']._serialized_start=404
  _globals['_RSANISTSIGVERVECTORS']._serialized_end=546
# @@protoc_insertion_point(module_scope)
