# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: falcon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x61lcon.proto\x12\rcrypto_condor\"\x93\x01\n\x11\x46\x61lconNistKatTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0c\n\x04seed\x18\x02 \x01(\t\x12\x0c\n\x04mlen\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\n\n\x02pk\x18\x05 \x01(\t\x12\n\n\x02sk\x18\x06 \x01(\t\x12\r\n\x05smlen\x18\x07 \x01(\x05\x12\n\n\x02sm\x18\x08 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"U\n\x14\x46\x61lconNistKatVectors\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x05tests\x18\x02 \x03(\x0b\x32 .crypto_condor.FalconNistKatTestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'falcon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FALCONNISTKATTEST']._serialized_start=32
  _globals['_FALCONNISTKATTEST']._serialized_end=179
  _globals['_FALCONNISTKATVECTORS']._serialized_start=181
  _globals['_FALCONNISTKATVECTORS']._serialized_end=266
# @@protoc_insertion_point(module_scope)
