# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sha.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsha.proto\x12\rcrypto_condor\"H\n\x0bShaNistTest\x12\x0b\n\x03len\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\n\n\x02md\x18\x03 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"M\n\x0eShaNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12)\n\x05tests\x18\x02 \x03(\x0b\x32\x1a.crypto_condor.ShaNistTest\"\xab\x01\n\x18ShaMonteCarloNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\t\x12\x41\n\x05tests\x18\x03 \x03(\x0b\x32\x32.crypto_condor.ShaMonteCarloNistVectors.TestsEntry\x1a,\n\nTestsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\rShakeNistTest\x12\x0b\n\x03len\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"e\n\x10ShakeNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\noutput_len\x18\x02 \x01(\x05\x12+\n\x05tests\x18\x03 \x03(\x0b\x32\x1c.crypto_condor.ShakeNistTest\"\xc6\x01\n\x15ShakeMonteNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07max_len\x18\x03 \x01(\x05\x12\x0f\n\x07min_len\x18\x04 \x01(\x05\x12>\n\x05tests\x18\x05 \x03(\x0b\x32/.crypto_condor.ShakeMonteNistVectors.TestsEntry\x1a,\n\nTestsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"l\n\x15ShakeVariableNistTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x12\n\noutput_len\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0e\n\x06output\x18\x04 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"a\n\x18ShakeVariableNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x33\n\x05tests\x18\x03 \x03(\x0b\x32$.crypto_condor.ShakeVariableNistTestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sha_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHAMONTECARLONISTVECTORS_TESTSENTRY._options = None
  _SHAMONTECARLONISTVECTORS_TESTSENTRY._serialized_options = b'8\001'
  _SHAKEMONTENISTVECTORS_TESTSENTRY._options = None
  _SHAKEMONTENISTVECTORS_TESTSENTRY._serialized_options = b'8\001'
  _globals['_SHANISTTEST']._serialized_start=28
  _globals['_SHANISTTEST']._serialized_end=100
  _globals['_SHANISTVECTORS']._serialized_start=102
  _globals['_SHANISTVECTORS']._serialized_end=179
  _globals['_SHAMONTECARLONISTVECTORS']._serialized_start=182
  _globals['_SHAMONTECARLONISTVECTORS']._serialized_end=353
  _globals['_SHAMONTECARLONISTVECTORS_TESTSENTRY']._serialized_start=309
  _globals['_SHAMONTECARLONISTVECTORS_TESTSENTRY']._serialized_end=353
  _globals['_SHAKENISTTEST']._serialized_start=355
  _globals['_SHAKENISTTEST']._serialized_end=433
  _globals['_SHAKENISTVECTORS']._serialized_start=435
  _globals['_SHAKENISTVECTORS']._serialized_end=536
  _globals['_SHAKEMONTENISTVECTORS']._serialized_start=539
  _globals['_SHAKEMONTENISTVECTORS']._serialized_end=737
  _globals['_SHAKEMONTENISTVECTORS_TESTSENTRY']._serialized_start=309
  _globals['_SHAKEMONTENISTVECTORS_TESTSENTRY']._serialized_end=353
  _globals['_SHAKEVARIABLENISTTEST']._serialized_start=739
  _globals['_SHAKEVARIABLENISTTEST']._serialized_end=847
  _globals['_SHAKEVARIABLENISTVECTORS']._serialized_start=849
  _globals['_SHAKEVARIABLENISTVECTORS']._serialized_end=946
# @@protoc_insertion_point(module_scope)
