# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _sha/sha.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e_sha/sha.proto\x12\rcrypto_condor\"3\n\x0bShaNistTest\x12\x0b\n\x03len\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x12\n\n\x02md\x18\x03 \x01(\x0c\"M\n\x0eShaNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12)\n\x05tests\x18\x02 \x03(\x0b\x32\x1a.crypto_condor.ShaNistTest\"\xbd\x01\n\x18ShaMonteCarloNistVectors\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\x0c\x12M\n\x0b\x63heckpoints\x18\x03 \x03(\x0b\x32\x38.crypto_condor.ShaMonteCarloNistVectors.CheckpointsEntry\x1a\x32\n\x10\x43heckpointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_sha.sha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHAMONTECARLONISTVECTORS_CHECKPOINTSENTRY']._loaded_options = None
  _globals['_SHAMONTECARLONISTVECTORS_CHECKPOINTSENTRY']._serialized_options = b'8\001'
  _globals['_SHANISTTEST']._serialized_start=33
  _globals['_SHANISTTEST']._serialized_end=84
  _globals['_SHANISTVECTORS']._serialized_start=86
  _globals['_SHANISTVECTORS']._serialized_end=163
  _globals['_SHAMONTECARLONISTVECTORS']._serialized_start=166
  _globals['_SHAMONTECARLONISTVECTORS']._serialized_end=355
  _globals['_SHAMONTECARLONISTVECTORS_CHECKPOINTSENTRY']._serialized_start=305
  _globals['_SHAMONTECARLONISTVECTORS_CHECKPOINTSENTRY']._serialized_end=355
# @@protoc_insertion_point(module_scope)
