# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: _sha/sha.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    '_sha/sha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e_sha/sha.proto\x12\rcrypto_condor\"\\\n\x07ShaTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\x0b\n\x03msg\x18\x05 \x01(\x0c\x12\n\n\x02md\x18\x06 \x01(\x0c\"\xc7\x01\n\tShaMcTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\x0c\n\x04seed\x18\x05 \x01(\x0c\x12>\n\x0b\x63heckpoints\x18\x06 \x03(\x0b\x32).crypto_condor.ShaMcTest.CheckpointsEntry\x1a\x32\n\x10\x43heckpointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\xa1\x02\n\nShaVectors\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bsource_desc\x18\x02 \x01(\t\x12\x12\n\nsource_url\x18\x03 \x01(\t\x12\x12\n\ncompliance\x18\x04 \x01(\x08\x12\x33\n\x05notes\x18\x05 \x03(\x0b\x32$.crypto_condor.ShaVectors.NotesEntry\x12%\n\x05tests\x18\x06 \x03(\x0b\x32\x16.crypto_condor.ShaTest\x12)\n\x07mc_test\x18\x07 \x01(\x0b\x32\x18.crypto_condor.ShaMcTest\x12\x11\n\talgorithm\x18\x08 \x01(\t\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_sha.sha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHAMCTEST_CHECKPOINTSENTRY']._loaded_options = None
  _globals['_SHAMCTEST_CHECKPOINTSENTRY']._serialized_options = b'8\001'
  _globals['_SHAVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_SHAVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_SHATEST']._serialized_start=33
  _globals['_SHATEST']._serialized_end=125
  _globals['_SHAMCTEST']._serialized_start=128
  _globals['_SHAMCTEST']._serialized_end=327
  _globals['_SHAMCTEST_CHECKPOINTSENTRY']._serialized_start=277
  _globals['_SHAMCTEST_CHECKPOINTSENTRY']._serialized_end=327
  _globals['_SHAVECTORS']._serialized_start=330
  _globals['_SHAVECTORS']._serialized_end=619
  _globals['_SHAVECTORS_NOTESENTRY']._serialized_start=575
  _globals['_SHAVECTORS_NOTESENTRY']._serialized_end=619
# @@protoc_insertion_point(module_scope)
