# generated by datamodel-codegen:
#   filename:  mldsa_verify_schema.json
#   timestamp: 2026-06-16T18:19:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Schema(Enum):
    mldsa_verify_schema_json = 'mldsa_verify_schema.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class Type(Enum):
    MlDsaVerify = 'MlDsaVerify'


class MlDsaVerifyTestVector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int = Field(..., description='Identifier of the test case')
    comment: str = Field(..., description='A brief description of the test case')
    msg: str = Field(..., description='The message to verify')
    ctx: str | None = Field(
        None,
        description='[optional] The additional context string (empty if not provided)',
    )
    sig: str = Field(..., description='The encoded signature')
    result: Result
    flags: list[str] = Field(..., description='A list of flags')


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class MlDsaVerifyTestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    publicKey: str = Field(..., description='Encoded ML-DSA public key')
    publicKeyDer: str = Field(
        ..., description='Public key as a DER-encoded SubjectPublicKeyInfo'
    )
    tests: list[MlDsaVerifyTestVector]
    source: Source | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: str = Field(..., description='the primitive tested in the test file')
    generatorVersion: str | None = Field(
        None,
        deprecated=True,
        description='DEPRECATED: prefer "source" property in test group',
    )
    header: list[str] = Field(..., description='additional documentation')
    notes: Notes
    numberOfTests: int = Field(
        ..., description='the number of test vectors in this test'
    )
    schema_: Schema = Field(..., alias='schema')
    testGroups: list[MlDsaVerifyTestGroup]
