# generated by datamodel-codegen:
#   filename:  mldsa_sign_noseed_schema.json
#   timestamp: 2026-07-03T09:24:37+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Schema(Enum):
    mldsa_sign_noseed_schema_json = 'mldsa_sign_noseed_schema.json'


class Source(BaseModel):
    name: constr(min_length=1)
    version: constr(min_length=1)


class NoteEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, description='A description of the flag')
    bugType: str = Field(..., description='The type of the bug tested for')
    effect: str | None = Field(
        None, description='The expected effect of failing the test vector'
    )
    links: list[str] | None = Field(
        None, description='A list of potentially related references'
    )
    cves: list[str] | None = Field(
        None, description='A list of potentially related CVEs'
    )


class Result(Enum):
    valid = 'valid'
    invalid = 'invalid'
    acceptable = 'acceptable'


class Type(Enum):
    MlDsaSign = 'MlDsaSign'


class MlDsaSignTestVector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tcId: int = Field(..., description='Identifier of the test case')
    comment: str = Field(..., description='A brief description of the test case')
    msg: str | None = Field(
        None,
        description='[optional] The message to sign (if omitted, mu is provided to use with Sign_internal)',
    )
    ctx: str | None = Field(
        None,
        description='[optional] The additional context string (if omitted, the context input is empty)',
    )
    rnd: str | None = Field(
        None,
        description='[optional] The 32-byte random value (if omitted, implicitly all zeroes for deterministic signing)',
    )
    mu: str | None = Field(
        None,
        description='[optional] The 64-byte μ value (omitted in case of expected failure)',
    )
    sig: str = Field(
        ..., description='The encoded signature (empty in case of expected failure)'
    )
    result: Result
    flags: list[str] = Field(..., description='A list of flags')


class Notes(RootModel[dict[str, NoteEntry]]):
    root: dict[str, NoteEntry]


class MlDsaSignNoSeedTestGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    privateKey: str = Field(..., description='Encoded ML-DSA private key')
    publicKey: str | None = Field(
        ...,
        description='Encoded ML-DSA public key derived from the private key, or null if the private key is invalid',
    )
    tests: list[MlDsaSignTestVector]
    source: Source


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: str = Field(..., description='the primitive tested in the test file')
    header: list[str] = Field(..., description='additional documentation')
    notes: Notes
    numberOfTests: int = Field(
        ..., description='the number of test vectors in this test'
    )
    schema_: Schema = Field(..., alias='schema')
    testGroups: list[MlDsaSignNoSeedTestGroup]
