# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _ecdsa/ecdsa.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12_ecdsa/ecdsa.proto\x12\rcrypto_condor\"u\n\x0f\x45\x63\x64saSigVerTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\x0b\n\x03msg\x18\x05 \x01(\x0c\x12\x0b\n\x03sig\x18\x06 \x01(\x0c\x12\x0e\n\x06pubkey\x18\x07 \x01(\x0c\"\x98\x02\n\x12\x45\x63\x64saSigVerVectors\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bsource_desc\x18\x02 \x01(\t\x12\x12\n\nsource_url\x18\x03 \x01(\t\x12\x12\n\ncompliance\x18\x04 \x01(\x08\x12;\n\x05notes\x18\x05 \x03(\x0b\x32,.crypto_condor.EcdsaSigVerVectors.NotesEntry\x12\r\n\x05\x63urve\x18\x06 \x01(\t\x12\x0c\n\x04hash\x18\x07 \x01(\t\x12-\n\x05tests\x18\x08 \x03(\x0b\x32\x1e.crypto_condor.EcdsaSigVerTest\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"c\n\x0f\x45\x63\x64saSigGenTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\x0b\n\x03msg\x18\x05 \x01(\x0c\x12\t\n\x01\x64\x18\x06 \x01(\x0c\"\x98\x02\n\x12\x45\x63\x64saSigGenVectors\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bsource_desc\x18\x02 \x01(\t\x12\x12\n\nsource_url\x18\x03 \x01(\t\x12\x12\n\ncompliance\x18\x04 \x01(\x08\x12;\n\x05notes\x18\x05 \x03(\x0b\x32,.crypto_condor.EcdsaSigGenVectors.NotesEntry\x12\r\n\x05\x63urve\x18\x06 \x01(\t\x12\x0c\n\x04hash\x18\x07 \x01(\t\x12-\n\x05tests\x18\x08 \x03(\x0b\x32\x1e.crypto_condor.EcdsaSigGenTest\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_ecdsa.ecdsa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECDSASIGVERVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_ECDSASIGVERVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_ECDSASIGGENVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_ECDSASIGGENVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_ECDSASIGVERTEST']._serialized_start=37
  _globals['_ECDSASIGVERTEST']._serialized_end=154
  _globals['_ECDSASIGVERVECTORS']._serialized_start=157
  _globals['_ECDSASIGVERVECTORS']._serialized_end=437
  _globals['_ECDSASIGVERVECTORS_NOTESENTRY']._serialized_start=393
  _globals['_ECDSASIGVERVECTORS_NOTESENTRY']._serialized_end=437
  _globals['_ECDSASIGGENTEST']._serialized_start=439
  _globals['_ECDSASIGGENTEST']._serialized_end=538
  _globals['_ECDSASIGGENVECTORS']._serialized_start=541
  _globals['_ECDSASIGGENVECTORS']._serialized_end=821
  _globals['_ECDSASIGGENVECTORS_NOTESENTRY']._serialized_start=393
  _globals['_ECDSASIGGENVECTORS_NOTESENTRY']._serialized_end=437
# @@protoc_insertion_point(module_scope)
