# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecdsa.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65\x63\x64sa.proto\x12\rcrypto_condor\"\x9a\x01\n\x13\x45\x63\x64saNistSigVerTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02qx\x18\x03 \x01(\t\x12\n\n\x02qy\x18\x04 \x01(\t\x12\t\n\x01r\x18\x05 \x01(\t\x12\t\n\x01s\x18\x06 \x01(\t\x12\x0e\n\x06result\x18\x07 \x01(\t\x12\x13\n\x0b\x66\x61il_reason\x18\x08 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"{\n\x16\x45\x63\x64saNistSigVerVectors\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63urve\x18\x02 \x01(\t\x12\x11\n\thash_algo\x18\x03 \x01(\t\x12\x31\n\x05tests\x18\x04 \x03(\x0b\x32\".crypto_condor.EcdsaNistSigVerTest\"\x8b\x01\n\x13\x45\x63\x64saNistSigGenTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\t\n\x01\x64\x18\x03 \x01(\t\x12\n\n\x02qx\x18\x04 \x01(\t\x12\n\n\x02qy\x18\x05 \x01(\t\x12\t\n\x01k\x18\x06 \x01(\t\x12\t\n\x01r\x18\x07 \x01(\t\x12\t\n\x01s\x18\x08 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"{\n\x16\x45\x63\x64saNistSigGenVectors\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63urve\x18\x02 \x01(\t\x12\x11\n\thash_algo\x18\x03 \x01(\t\x12\x31\n\x05tests\x18\x04 \x03(\x0b\x32\".crypto_condor.EcdsaNistSigGenTestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecdsa_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ECDSANISTSIGVERTEST']._serialized_start=31
  _globals['_ECDSANISTSIGVERTEST']._serialized_end=185
  _globals['_ECDSANISTSIGVERVECTORS']._serialized_start=187
  _globals['_ECDSANISTSIGVERVECTORS']._serialized_end=310
  _globals['_ECDSANISTSIGGENTEST']._serialized_start=313
  _globals['_ECDSANISTSIGGENTEST']._serialized_end=452
  _globals['_ECDSANISTSIGGENVECTORS']._serialized_start=454
  _globals['_ECDSANISTSIGGENVECTORS']._serialized_end=577
# @@protoc_insertion_point(module_scope)
