# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _mldsa/mldsa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12_mldsa/mldsa.proto\x12\rcrypto_condor\"\x88\x02\n\tMldsaTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\x0b\n\x03msg\x18\x05 \x01(\x0c\x12\n\n\x02pk\x18\x06 \x01(\x0c\x12\n\n\x02sk\x18\x07 \x01(\x0c\x12\x0b\n\x03sig\x18\x08 \x01(\x0c\x12\x0b\n\x03\x63tx\x18\t \x01(\x0c\x12\x0c\n\x04seed\x18\n \x01(\x0c\x12\x0b\n\x03rnd\x18\x0b \x01(\x0c\x12\x15\n\rdeterministic\x18\x0c \x01(\x08\x12\x0f\n\x07preHash\x18\r \x01(\x08\x12\x1a\n\x12signatureInterface\x18\x0e \x01(\t\x12\x12\n\nexternalMu\x18\x0f \x01(\x08\x12\x0f\n\x07hashAlg\x18\x10 \x01(\t\"\x9e\x02\n\x0cMldsaVectors\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bsource_desc\x18\x02 \x01(\t\x12\x12\n\nsource_url\x18\x03 \x01(\t\x12\x12\n\ncompliance\x18\x04 \x01(\x08\x12\x35\n\x05notes\x18\x05 \x03(\x0b\x32&.crypto_condor.MldsaVectors.NotesEntry\x12\x10\n\x08paramset\x18\x06 \x01(\t\x12\'\n\x05tests\x18\x07 \x03(\x0b\x32\x18.crypto_condor.MldsaTest\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\x0f\n\x07prehash\x18\t \x01(\x08\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_mldsa.mldsa_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MLDSAVECTORS_NOTESENTRY._options = None
  _MLDSAVECTORS_NOTESENTRY._serialized_options = b'8\001'
  _MLDSATEST._serialized_start=38
  _MLDSATEST._serialized_end=302
  _MLDSAVECTORS._serialized_start=305
  _MLDSAVECTORS._serialized_end=591
  _MLDSAVECTORS_NOTESENTRY._serialized_start=547
  _MLDSAVECTORS_NOTESENTRY._serialized_end=591
# @@protoc_insertion_point(module_scope)
