# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\taes.proto\x12\rcrypto_condor\"\xba\x01\n\x0b\x41\x65sNistTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x11\n\tplaintext\x18\x04 \x01(\t\x12\x12\n\nciphertext\x18\x05 \x01(\t\x12\n\n\x02iv\x18\x06 \x01(\t\x12\x0b\n\x03\x61\x61\x64\x18\x07 \x01(\t\x12\x0b\n\x03tag\x18\x08 \x01(\t\x12\x10\n\x08is_valid\x18\n \x01(\x08\x12\x0f\n\x07\x65ncrypt\x18\x0b \x01(\x08\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"k\n\x0e\x41\x65sNistVectors\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x05tests\x18\x02 \x03(\x0b\x32\x1a.crypto_condor.AesNistTest\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x12\n\nkey_length\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AESNISTTEST']._serialized_start=29
  _globals['_AESNISTTEST']._serialized_end=215
  _globals['_AESNISTVECTORS']._serialized_start=217
  _globals['_AESNISTVECTORS']._serialized_end=324
# @@protoc_insertion_point(module_scope)
