# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: _aes/aes.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    '_aes/aes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e_aes/aes.proto\x12\rcrypto_condor\"\x8e\x01\n\x07\x41\x65sTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t\x12\x0b\n\x03key\x18\x05 \x01(\x0c\x12\n\n\x02pt\x18\x06 \x01(\x0c\x12\n\n\x02\x63t\x18\x07 \x01(\x0c\x12\n\n\x02iv\x18\x08 \x01(\x0c\x12\x0b\n\x03\x61\x61\x64\x18\t \x01(\x0c\x12\x0b\n\x03tag\x18\n \x01(\x0c\"\xa3\x02\n\nAesVectors\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bsource_desc\x18\x02 \x01(\t\x12\x12\n\nsource_url\x18\x03 \x01(\t\x12\x12\n\ncompliance\x18\x04 \x01(\x08\x12\x33\n\x05notes\x18\x05 \x03(\x0b\x32$.crypto_condor.AesVectors.NotesEntry\x12%\n\x05tests\x18\x06 \x03(\x0b\x32\x16.crypto_condor.AesTest\x12\x0c\n\x04mode\x18\x07 \x01(\t\x12\x0e\n\x06keylen\x18\x08 \x01(\x05\x12\x0f\n\x07\x65ncrypt\x18\t \x01(\x08\x12\x0f\n\x07\x64\x65\x63rypt\x18\n \x01(\x08\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_aes.aes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AESVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_AESVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_AESTEST']._serialized_start=34
  _globals['_AESTEST']._serialized_end=176
  _globals['_AESVECTORS']._serialized_start=179
  _globals['_AESVECTORS']._serialized_end=470
  _globals['_AESVECTORS_NOTESENTRY']._serialized_start=426
  _globals['_AESVECTORS_NOTESENTRY']._serialized_end=470
# @@protoc_insertion_point(module_scope)
