"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Ed25519Test(google.protobuf.message.Message):
    """A single Ed25519 test vector."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    SK_FIELD_NUMBER: builtins.int
    PK_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SIG_FIELD_NUMBER: builtins.int
    CTX_FIELD_NUMBER: builtins.int
    id: builtins.int
    """The test ID, unique in its set of vectors."""
    type: builtins.str
    """The type of test. One of: valid, invalid, acceptable."""
    comment: builtins.str
    """A comment on the test."""
    sk: builtins.bytes
    """The raw private key."""
    pk: builtins.bytes
    """The raw public key."""
    msg: builtins.bytes
    """The message."""
    sig: builtins.bytes
    """The signature."""
    ctx: builtins.bytes
    """(For Ed25519ctx only) The context string."""
    @property
    def flags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Flags that categorize this test."""

    def __init__(
        self,
        *,
        id: builtins.int = ...,
        type: builtins.str = ...,
        comment: builtins.str = ...,
        flags: collections.abc.Iterable[builtins.str] | None = ...,
        sk: builtins.bytes = ...,
        pk: builtins.bytes = ...,
        msg: builtins.bytes = ...,
        sig: builtins.bytes = ...,
        ctx: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["comment", b"comment", "ctx", b"ctx", "flags", b"flags", "id", b"id", "msg", b"msg", "pk", b"pk", "sig", b"sig", "sk", b"sk", "type", b"type"]) -> None: ...

global___Ed25519Test = Ed25519Test

@typing.final
class Ed25519Vectors(google.protobuf.message.Message):
    """A set of Ed25519 test vectors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NotesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SOURCE_FIELD_NUMBER: builtins.int
    SOURCE_DESC_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    COMPLIANCE_FIELD_NUMBER: builtins.int
    NOTES_FIELD_NUMBER: builtins.int
    TESTS_FIELD_NUMBER: builtins.int
    VARIANT_FIELD_NUMBER: builtins.int
    SIGN_FIELD_NUMBER: builtins.int
    VERIFY_FIELD_NUMBER: builtins.int
    source: builtins.str
    """The source of the test vectors."""
    source_desc: builtins.str
    """Description of the source."""
    source_url: builtins.str
    """The URL of the source."""
    compliance: builtins.bool
    """Whether these are compliance test vectors or not."""
    variant: builtins.str
    """The Ed25519 variant, one of: ed25519, ed25519ctx, ed25519ph."""
    sign: builtins.bool
    """Whether the test vectors can be used to test signing."""
    verify: builtins.bool
    """Whether the test vectors can be used to test verifying."""
    @property
    def notes(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """A dictionary of test flags and their description."""

    @property
    def tests(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Ed25519Test]:
        """The test vectors."""

    def __init__(
        self,
        *,
        source: builtins.str = ...,
        source_desc: builtins.str = ...,
        source_url: builtins.str = ...,
        compliance: builtins.bool = ...,
        notes: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        tests: collections.abc.Iterable[global___Ed25519Test] | None = ...,
        variant: builtins.str = ...,
        sign: builtins.bool = ...,
        verify: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["compliance", b"compliance", "notes", b"notes", "sign", b"sign", "source", b"source", "source_desc", b"source_desc", "source_url", b"source_url", "tests", b"tests", "variant", b"variant", "verify", b"verify"]) -> None: ...

global___Ed25519Vectors = Ed25519Vectors
