# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _ECDH/ECDH.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10_ECDH/ECDH.proto\x12\rcrypto_condor\"u\n\x0c\x45\x63\x64hNistTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0e\n\x06peer_x\x18\x02 \x01(\x0c\x12\x0e\n\x06peer_y\x18\x03 \x01(\x0c\x12\r\n\x05own_d\x18\x04 \x01(\x0c\x12\r\n\x05own_x\x18\x05 \x01(\x0c\x12\r\n\x05own_y\x18\x06 \x01(\x0c\x12\t\n\x01z\x18\x07 \x01(\x0c\"L\n\x0f\x45\x63\x64hNistVectors\x12\r\n\x05\x63urve\x18\x01 \x01(\t\x12*\n\x05tests\x18\x02 \x03(\x0b\x32\x1b.crypto_condor.EcdhNistTest\"\x81\x01\n\x12\x45\x63\x64hWycheproofTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x0e\n\x06public\x18\x03 \x01(\x0c\x12\x0f\n\x07private\x18\x04 \x01(\x0c\x12\x0e\n\x06shared\x18\x05 \x01(\x0c\x12\x0e\n\x06result\x18\x06 \x01(\t\x12\r\n\x05\x66lags\x18\x07 \x03(\t\"v\n\x13\x45\x63\x64hWycheproofGroup\x12\r\n\x05\x63urve\x18\x01 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x30\n\x05tests\x18\x04 \x03(\x0b\x32!.crypto_condor.EcdhWycheproofTest\"\xb2\x02\n\x15\x45\x63\x64hWycheproofVectors\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x19\n\x11generator_version\x18\x02 \x01(\t\x12\x17\n\x0fnumber_of_tests\x18\x03 \x01(\x05\x12\x0e\n\x06header\x18\x04 \x01(\t\x12>\n\x05notes\x18\x05 \x03(\x0b\x32/.crypto_condor.EcdhWycheproofVectors.NotesEntry\x12\x0e\n\x06schema\x18\x06 \x01(\t\x12\x32\n\x06groups\x18\x07 \x03(\x0b\x32\".crypto_condor.EcdhWycheproofGroup\x12\x10\n\x08\x66ilename\x18\x0f \x01(\t\x1a,\n\nNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_ECDH.ECDH_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECDHWYCHEPROOFVECTORS_NOTESENTRY']._loaded_options = None
  _globals['_ECDHWYCHEPROOFVECTORS_NOTESENTRY']._serialized_options = b'8\001'
  _globals['_ECDHNISTTEST']._serialized_start=35
  _globals['_ECDHNISTTEST']._serialized_end=152
  _globals['_ECDHNISTVECTORS']._serialized_start=154
  _globals['_ECDHNISTVECTORS']._serialized_end=230
  _globals['_ECDHWYCHEPROOFTEST']._serialized_start=233
  _globals['_ECDHWYCHEPROOFTEST']._serialized_end=362
  _globals['_ECDHWYCHEPROOFGROUP']._serialized_start=364
  _globals['_ECDHWYCHEPROOFGROUP']._serialized_end=482
  _globals['_ECDHWYCHEPROOFVECTORS']._serialized_start=485
  _globals['_ECDHWYCHEPROOFVECTORS']._serialized_end=791
  _globals['_ECDHWYCHEPROOFVECTORS_NOTESENTRY']._serialized_start=747
  _globals['_ECDHWYCHEPROOFVECTORS_NOTESENTRY']._serialized_end=791
# @@protoc_insertion_point(module_scope)
