# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sphincs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsphincs.proto\x12\rcrypto_condor\"\x94\x01\n\x12SphincsNistKatTest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0c\n\x04seed\x18\x02 \x01(\t\x12\x0c\n\x04mlen\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\n\n\x02pk\x18\x05 \x01(\t\x12\n\n\x02sk\x18\x06 \x01(\t\x12\r\n\x05smlen\x18\x07 \x01(\x05\x12\n\n\x02sm\x18\x08 \x01(\t\x12\x13\n\x0bline_number\x18\x0f \x01(\x05\"W\n\x15SphincsNistKatVectors\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x30\n\x05tests\x18\x02 \x03(\x0b\x32!.crypto_condor.SphincsNistKatTestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sphincs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SPHINCSNISTKATTEST']._serialized_start=33
  _globals['_SPHINCSNISTKATTEST']._serialized_end=181
  _globals['_SPHINCSNISTKATVECTORS']._serialized_start=183
  _globals['_SPHINCSNISTKATVECTORS']._serialized_end=270
# @@protoc_insertion_point(module_scope)
