name: main

on: [push]

defaults:
  run:
    working-directory: ${{ github.workspace }}

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          export PYTHONDONTWRITEBYTECODE=1
          python --version; python -m pip --version
          python -m pip install poetry
          poetry --version
          poetry config virtualenvs.in-project true
          poetry install -vv
          source `poetry env info --path`/bin/activate

  lint:
    runs-on: ubuntu-22.04
    needs: [setup]
    steps:
      - run: make lint-ci

  type-check:
    runs-on: ubuntu-22.04
    needs: [setup]
    steps:
      - run: make type-check-ci

  test:
    runs-on: ubuntu-22.04
    needs: [lint,type-check]
    steps:
      - run: |
          make coverage-ci
          make doctest

  docs:
    runs-on: ubuntu-22.04
    needs: [lint,type-check]
    steps:
      - run: make docs

  upload-docs:
    if: success() && github.ref == 'refs/heads/main'
    needs: [test,docs]
    runs-on: ubuntu-22.04
    steps:
      - name: Build docs
        run: make pages-ci
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/public

  pages:
    needs: [upload-docs]
    if: success() && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Publish to pages
        id: deployment
        uses: actions/deploy-pages@v4

  build:
    needs: [test,docs]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - run: make build-ci

  publish:
    needs: [pages,build]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - run: make publish-ci
