name: test

on:
  workflow_run:
    workflows: [setup]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: make lint-ci

  type-check:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: make type-check-ci

  test:
    runs-on: ubuntu-22.04
    needs: [lint,type-check]
    steps:
      - run: |
          make coverage-ci
          make doctest

  docs:
    runs-on: ubuntu-22.04
    needs: [lint,type-check]
    steps:
      - run: make docs
